global using DotNet6.GenericRepositoryInUnitOfWork.Database.Context;
global using DotNet6.GenericRepositoryInUnitOfWork.Database.Entity;
global using DotNet6.GenericRepositoryInUnitOfWork.GenericRepository;
global using DotNet6.GenericRepositoryInUnitOfWork.UoW;
global using Microsoft.EntityFrameworkCore;